import type { FeatureHubItem } from "../types/types";

export const APP_FEATURE_CATALOG: FeatureHubItem[] = [
  {
    id: "home-dashboard",
    module: "home",
    title: "Home",
    description: "Overview, shortcuts, and recent activity.",
    route: "/(tabs)/home",
  },
  {
    id: "payments-overview",
    module: "transactions",
    title: "Transactions",
    description: "Income, expense, and payment history.",
    route: "/(tabs)/transactions",
  },
  {
    id: "send-money",
    module: "transfers",
    title: "Transfers",
    description: "Beneficiaries with saved and scheduled transfers.",
    route: "/(tabs)/inventory",
  },
  {
    id: "quick-pos",
    module: "pos",
    title: "POS",
    description: "Billing with stock deduction and account posting.",
    route: "/(tabs)/quick-pos",
  },
  {
    id: "cash-bank-list",
    module: "cashBank",
    title: "Accounts",
    description: "Manage accounts, opening balances, and primary account.",
    route: "/cash-bank",
  },
  {
    id: "home-edit-shortcuts",
    module: "home",
    title: "Edit Home Shortcuts",
    description: "Customize shortcut order and visibility for dashboard.",
    route: "/edit-shortcuts",
  },
  {
    id: "notifications-list",
    module: "notifications",
    title: "Notifications",
    description: "Timeline from transaction and scheduled-transfer activity.",
    route: "/notifications",
  },
  {
    id: "parties-list",
    module: "parties",
    title: "Contacts",
    description: "Manage customer and supplier contacts.",
    route: "/parties",
  },
  {
    id: "reports-list",
    module: "reports",
    title: "Reports",
    description: "Financial and operational summary reports.",
    route: "/reports",
  },
  {
    id: "transactions-quick-entry",
    module: "transactions",
    title: "Quick Add",
    description: "Fast transaction entry with account posting.",
    route: "/quick-entry",
  },
  {
    id: "profile-selection",
    module: "profile",
    title: "Switch Profile",
    description: "Switch active profile for this account.",
    route: "/profile-selection",
  },
  {
    id: "profile-create-business",
    module: "profile",
    title: "Create Business",
    description: "Create a business with category assignment.",
    route: "/create-business",
  },
  {
    id: "profile-download-data",
    module: "profile",
    title: "Export Data",
    description: "Generate structured profile export from DB.",
    route: "/(auth)/download-data",
  },
  {
    id: "language-selection",
    module: "auth",
    title: "Language",
    description: "Manage app language preference.",
    route: "/(auth)/language",
  },
];
