import type { MoreFeatureItem } from "../viewModel/more.viewModel";

export const APP_FEATURE_CATALOG: MoreFeatureItem[] = [
  {
    id: "home-dashboard",
    module: "home",
    title: "Home Dashboard",
    description: "Business summary, shortcuts, and recent activity.",
    status: "implemented",
    databaseConnected: true,
    route: "/(tabs)/home",
  },
  {
    id: "payments-overview",
    module: "transactions",
    title: "Payments",
    description: "Payment in/out entry and history.",
    status: "implemented",
    databaseConnected: true,
    route: "/(tabs)/transactions",
  },
  {
    id: "send-money",
    module: "transfers",
    title: "Send Money",
    description: "Beneficiaries with saved and scheduled transfer records.",
    status: "implemented",
    databaseConnected: true,
    route: "/(tabs)/inventory",
  },
  {
    id: "quick-pos",
    module: "pos",
    title: "Counter Sale (Quick POS)",
    description: "Fast billing with stock deduction and account posting.",
    status: "implemented",
    databaseConnected: true,
    route: "/(tabs)/quick-pos",
  },
  {
    id: "cash-bank-list",
    module: "cashBank",
    title: "Cash & Bank",
    description: "Manage accounts, opening balances, and primary account.",
    status: "implemented",
    databaseConnected: true,
    route: "/cash-bank",
  },
  {
    id: "home-edit-shortcuts",
    module: "home",
    title: "Edit Home Shortcuts",
    description: "Customize shortcut order and visibility for dashboard.",
    status: "implemented",
    databaseConnected: true,
    route: "/edit-shortcuts",
  },
  {
    id: "notifications-list",
    module: "notifications",
    title: "Notifications",
    description: "Timeline from transaction and scheduled-transfer activity.",
    status: "implemented",
    databaseConnected: true,
    route: "/notifications",
  },
  {
    id: "parties-list",
    module: "parties",
    title: "Parties",
    description: "Manage customer/supplier beneficiary records.",
    status: "implemented",
    databaseConnected: true,
    route: "/parties",
  },
  {
    id: "reports-list",
    module: "reports",
    title: "Reports",
    description: "Financial and operational summary reports.",
    status: "implemented",
    databaseConnected: true,
    route: "/reports",
  },
  {
    id: "transactions-quick-entry",
    module: "transactions",
    title: "Quick Entry",
    description: "Fast income/expense entry with account posting.",
    status: "implemented",
    databaseConnected: true,
    route: "/quick-entry",
  },
  {
    id: "profile-selection",
    module: "profile",
    title: "Profile Selection",
    description: "Switch active profile for this account.",
    status: "implemented",
    databaseConnected: true,
    route: "/profile-selection",
  },
  {
    id: "profile-create-business",
    module: "profile",
    title: "Create Business Profile",
    description: "Create business profile with category assignment.",
    status: "implemented",
    databaseConnected: true,
    route: "/create-business",
  },
  {
    id: "profile-download-data",
    module: "profile",
    title: "Download Data",
    description: "Generate structured profile data snapshot from DB.",
    status: "implemented",
    databaseConnected: true,
    route: "/(auth)/download-data",
  },
  {
    id: "language-selection",
    module: "auth",
    title: "Language Selection",
    description: "Language preference persisted in app settings.",
    status: "implemented",
    databaseConnected: true,
    route: "/(auth)/language",
  },
  {
    id: "phone-auth",
    module: "auth",
    title: "Phone Auth",
    description: "Country, phone validation, and OTP request.",
    status: "implemented",
    databaseConnected: true,
    route: "/(auth)/phone-auth",
  },
  {
    id: "otp-verification",
    module: "auth",
    title: "OTP Verification",
    description: "OTP verify and session upsert.",
    status: "implemented",
    databaseConnected: true,
    route: "/(auth)/otp-verification",
  },
  {
    id: "profile-select-auth",
    module: "auth",
    title: "Auth Profile Selection",
    description: "Create/select profile after verification.",
    status: "implemented",
    databaseConnected: true,
    route: "/(auth)/select-profile",
  },
  {
    id: "more-logout",
    module: "more",
    title: "Logout",
    description: "Session clear and secure sign-out.",
    status: "implemented",
    databaseConnected: true,
  },
];
